services:
  qdrant:
    image: qdrant/qdrant:v1.16.3
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    configs:  
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./data/qdrant_data:/qdrant/storage

configs:
  qdrant_config:
    content: |
      log_level: INFO
